dbt-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.27.16.1
      user: postgres
      password: postgres
      port: 5432
      dbname: dbt_local_proj
      schema: dbt_test
      threads: 3
      keepalives_idle: 0 # default 0, indicating the system default