name: 'my_dbtpostgres_project'
version: '1.0.0'

profile: dbt-postgres

model-paths: ["models"]
# analysis-paths: ["analysis"] 
# test-paths: ["tests"]
# seed-paths: ["data"]
# macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"