apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-admin
  namespace: airflow-local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-admin-role
  namespace: airflow-local
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-admin-rolebinding
  namespace: airflow-local
subjects:
  - kind: ServiceAccount
    name: airflow-admin
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-admin-role
  apiGroup: rbac.authorization.k8s.io
