apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-01
  namespace: local-airflow
  labels:
    app: airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi