name: local-airflow-actions

# on: # specify the build to trigger the automated ci/cd
#     push:
#         branches:
#             - "main"
on:
  push:
    branches: [ main ]
    
env: 
  REGISTRY: docker.io
  IMAGE_NAME: anompu/airflow-293-hub


run-name: running tests for buildimage
jobs:

  check-requirements:
    name: Check requierements file
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.check_changes.outputs.any_changed}}
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      
      -
        name: Check for changes
        id: check_changes
        uses: tj-actions/changed-files@v34
        with:
          working-directory: .
          files: requirements.txt
      - 
        name: Run step if any file(s) in the docs folder change
        if: steps.check_changes.outputs.any_changed == 'true'
        run: echo UI-kit is affected
      - 
        name: Prevent from running
        if: steps.check_changes.outputs.any_changed != 'true'
        run: echo No changes
  
  test1:
    name: Checksrequierements file
    needs: 
      - check-requirements    
    runs-on: ubuntu-latest
    steps:
      -
        name: testPrint
        run: |
          echo ${{ needs.check-requirements.outputs.output1 }}
  
  build:
    name: Build Docker-Image
    needs:
      - check-requirements
    if: needs.check-requirements.outputs.output1 == 'true'
    runs-on: ubuntu-latest
    steps:
      # - run: |
      #     echo ${{ needs.check-requirements.result }}
          
          
      -
          name: Build existin Docker Image
          run: docker build . --file ./Dockerfile --tag anompu/airflow-293-hub:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
         # - # login to Docker Hub using the secrets provided
          #   name: Login to Docker Hub
          #   run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
         # -
          #   name: Push to DockerHub
          #   run: docker push anompu/airflow-293-hub:${{ secrets.MAJOR }}.${{ secrets.MINOR }}
          
          # -
          #   name: Update Minor version
          #   uses: hmanzur/actions-set-secret@v2.0.0
          #   with:
          #     name: 'MINOR'
          #     value: $((${{ secrets.MINOR }}+1))
          #     repository: AnomP29/local-airflow
          #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
         
          # - name: Extract metadata for the Docker image
          #   id: meta
          #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          #   with:
          #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #     tags: |
          #         type=semver,pattern={{raw}}
          #         type=semver,pattern={{raw}},value=v1.0.0
         # - # create a build kit builder instance
          #   name: Set up Docker Buildx
          #   uses: docker/setup-buildx-action@v2
         # -
          #     name: Build and push
          #     uses: docker/build-push-action@v6
          #     with:
          #       context: .
          #       push: ${{ github.event_name != 'pull_request' }}
          #       tags: ${{ steps.meta.outputs.tags }}
          #       labels: ${{ steps.meta.outputs.labels }}



            
