name: local-airflow-actions

on: # specify the build to trigger the automated ci/cd
    push:
        branches:
            - "main"
env: 
  REGISTRY: docker.io
  IMAGE_NAME: anompu/airflow-293-hub


run-name: running tests for buildimage
jobs:
    build:
        name: Build Docker-Image
        runs-on: ubuntu-latest
        steps:
            - # checkout to the repository on the build machine
              name: Checkout
              uses: actions/checkout@v3

            - # login to Docker Hub using the secrets provided
              name: Login to Docker Hub
              run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            - name: Extract metadata for the Docker image
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: |
                    # minimal
                    type=match,pattern=\d.\d.\d
                    # define match group
                    type=match,pattern=v(.*),group=1
                    # use custom value instead of git tag
                    type=match,pattern=v(.*),group=1,value=v1.0.0

            - # create a build kit builder instance
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            -
                name: Build and push
                uses: docker/build-push-action@v6
                with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}



            
